adapter: mysql2            
host: 172.16.2.167                         # VM IP
port: 46504                          # VM Port 
database: t             # Database Name
username: ac11lmmreobb9zla                 # User Name
password: 'auye34mkj4vxs1mqxq74gpdwo3zn1ltg'                # Password
