adapter: mysql2            
host: 172.16.2.167                          # VM IP
port: 38923                          # VM Port 
database: t             # Database Name
username: a8z5d291jl3pdx2h                 # User Name
password: 'wz4ntbx3n7urzd1ey9lbtvh5lfmgzq69'                # Password
