adapter: mysql2            
host: 172.16.2.167                         # VM IP
port: 25178                          # VM Port 
database: t             # Database Name
username: ayiltj96nym2tz9l                 # User Name
password: 'an9zwa6u3qiyide5rph8hxpsnk0evsi6'                # Password
