adapter: mysql2            
host: 192.168.2.202                         # VM IP
port: 20868                          # VM Port 
database: t             # Database Name
username: afkjbifrlvccuq9b                 # User Name
password: 'amc541mgd62ypyxzlxvgpr1m6zwbfkdc'                # Password
